### PR TITLE
Add test for java.lang.String#intern()

### PR DESCRIPTION
**Pull request by chitoku-k**
The implementation is currently under the progress and this PR aims to add it along with the test.

See also: #120

### CODE REVIEW

**Comment by m3m0r7** [comment]
I'll change features as following.
- Allow to overwrite the constant pool.

Is it correct?

**Comment by m3m0r7** [comment]
@chitoku-k

**Comment by chitoku-k** [comment]
@memory-agape Probably that should make sense. For clarification,

1. Allow `String#intern()` to overwrite the constant pool.
2. Any literals that appear after the write operation will refer to (1).

And, please have a look at #120 as well.

**Comment by m3m0r7** [comment]
@chitoku-k 
Thanks 👍 
I'll try to implement.

**Comment by m3m0r7** [comment]
@chitoku-k 
You can add new tests.

**Comment by chitoku-k** [comment]
OK, I found a ridiculous edge case that isn't covered.

Whereas the following prints the expected result,

```java
String te = "te";
String st = "st";
String test = te + st;

System.out.println(System.identityHashCode(test)); // => 356573597

test.intern();
System.out.println(System.identityHashCode("test")); // => 356573597
```

the interning does not happen in JVM when a literal has already appeared in that scope:

```java
String te = "te";
String st = "st";
String test = te + st;

System.out.println(System.identityHashCode(test))  // => 356573597

// This line is added to make a literal appear before interned
String dummy = "test";

test.intern();
System.out.println(System.identityHashCode("test")); // => JVM: 1735600054, PHPJava: 356573597
```

Adding the failing test...

**Comment by m3m0r7** [comment]
Very sad (T_T)

**Comment by chitoku-k** [comment]
I think this PR finally got ready for reviewing!

**Comment by m3m0r7** [comment]
@chitoku-k 
Looks good to me!
Please merge this PR after fixing conflicted files.

**Review by m3m0r7 — APPROVED** [review]

**Pull request merged**
